In [1]:
import torch

In [2]:
a = torch.ones(3)
a

tensor([1., 1., 1.])

In [3]:
points = torch.zeros(6)

points[0] = 4.0
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0

In [4]:
points = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])
points

tensor([4., 1., 5., 3., 2., 1.])

In [5]:
torch.ones([5, 4])

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [6]:
A = torch.zeros([5, 3])
A.shape

torch.Size([5, 3])

In [7]:
A = A[torch.newaxis, :, :]
A.shape

torch.Size([1, 5, 3])

In [8]:
img_t = torch.randn(3, 5, 5)  # shape ([channels, rows, columns])
weights = torch.tensor([0.2126, 0.7152, 0.0722])

In [9]:
batch_t = torch.randn(2, 3, 5, 5)  # shape ([batch, channels, rows, columns])

In [10]:
img_gray_naive = img_t.mean(-3)
batch_gray_naive = batch_t.mean(-3)
img_gray_naive.shape, batch_gray_naive.shape

(torch.Size([5, 5]), torch.Size([2, 5, 5]))

In [11]:
weights.shape

torch.Size([3])

In [12]:
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze(-1)
unsqueezed_weights.shape

torch.Size([3, 1, 1])

In [13]:
img_t.shape

torch.Size([3, 5, 5])

In [14]:
img_weights = (img_t * unsqueezed_weights)
img_weights.shape

torch.Size([3, 5, 5])

In [15]:
weights_named = torch.tensor([0.216, 0.7152, 0.0722], names=["channels"])
weights_named

/var/folders/kd/gn_dg9w13px_cwn32p5bs4fc0000gn/T/ipykernel_30219/3403182555.py:1: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/c10/core/TensorImpl.h:1938.)
  weights_named = torch.tensor([0.216, 0.7152, 0.0722], names=["channels"])


tensor([0.2160, 0.7152, 0.0722], names=('channels',))

In [16]:
img_named = img_t.refine_names(..., "channels", "rows", "columns")
img_named.shape, img_named.names

(torch.Size([3, 5, 5]), ('channels', 'rows', 'columns'))

In [17]:
weights_aligned = weights_named.align_as(img_named)
weights_aligned

tensor([[[0.2160]],

        [[0.7152]],

        [[0.0722]]], names=('channels', 'rows', 'columns'))

In [18]:
A = torch.randn(3, 2, 3, names=["channels", "row", "columns"])
B = torch.randn(3, names=["channels"])

In [19]:
A.shape, A.names

(torch.Size([3, 2, 3]), ('channels', 'row', 'columns'))

In [20]:
B.shape, B.names

(torch.Size([3]), ('channels',))

In [21]:
B_align = B.align_as(A)
B_align.shape

torch.Size([3, 1, 1])

In [22]:
img_named.shape, img_named.names

(torch.Size([3, 5, 5]), ('channels', 'rows', 'columns'))

In [23]:
weights_named.shape, weights_named.names

(torch.Size([3]), ('channels',))

In [24]:
weights_aligned.shape, weights_aligned.names

(torch.Size([3, 1, 1]), ('channels', 'rows', 'columns'))

In [25]:
gray_named = (img_named * weights_aligned)

In [26]:
double_points = torch.ones(10, 2, dtype=torch.float64)
short_points = torch.tensor([[1, 2], [3, 4]], dtype=torch.int16)

In [27]:
short_points.dtype

torch.int16

In [28]:
double_points.dtype

torch.float64

In [29]:
a = torch.ones(3, 2, 1)
a_t = a.transpose(0, 1)
a_t.shape

torch.Size([2, 3, 1])

In [30]:
a = torch.ones(3, 2)
a_t = a.transpose(0, 1)
a_t.shape

torch.Size([2, 3])

In [31]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points.storage()

/var/folders/kd/gn_dg9w13px_cwn32p5bs4fc0000gn/T/ipykernel_30219/2923139482.py:2: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  points.storage()


 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [32]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1].clone()
second_point.storage_offset()
second_point[0] = 10
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [33]:
first_point = points[0]
first_point.storage_offset()

0

In [34]:
second_point.stride()
points.stride()

(2, 1)

In [35]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points.stride()

(2, 1)

In [36]:
points_T = points.T
points_T.stride()

(1, 2)

In [37]:
some_t = torch.ones(3, 4, 5)
transpose_t = some_t.transpose(0, 2)
some_t.shape, some_t.stride()

(torch.Size([3, 4, 5]), (20, 5, 1))

In [38]:
transpose_t.shape, transpose_t.stride()

(torch.Size([5, 4, 3]), (1, 5, 20))

In [39]:
points.is_contiguous()

True

In [40]:
points_T.is_contiguous()

False

In [41]:
points = points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_T = points.T
points_T

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [42]:
points.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [43]:
points_T.shape

torch.Size([2, 3])

In [44]:
points_T.stride()

(1, 2)

In [45]:
points_T_cont = points_T.contiguous()
points_T_cont

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [46]:
points_T_cont.stride()

(3, 1)

In [47]:
points_T_cont

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [48]:
points.is_contiguous()

True

In [49]:
device = torch.device("cuda" if torch.cuda.is_available()
                      else "mps" if torch.backends.mps.is_available()
                      else "cpu")
device

device(type='mps')

In [50]:
points_gpu = points.to(device=device)

In [51]:
points = 2 * points
points_gpu = 2 * points_gpu

In [52]:
points.device

device(type='cpu')

In [53]:
points_gpu.device

device(type='mps', index=0)

In [54]:
points_np = points.numpy()
points_np

array([[ 8.,  2.],
       [10.,  6.],
       [ 4.,  2.]], dtype=float32)

In [55]:
points = torch.from_numpy(points_np)

In [56]:
points.dtype

torch.float32

In [57]:
torch.save(points, "points.pt")

In [58]:
points_file = torch.load("points.pt")

In [59]:
points_file

tensor([[ 8.,  2.],
        [10.,  6.],
        [ 4.,  2.]])

In [60]:
import h5py


f = h5py.File("data/outpoints.hdf5", "w")
dset = f.create_dataset("coords", data=points.numpy())
f.close()

In [61]:
f = h5py.File("data/outpoints.hdf5", "r")
dset = f["coords"]
last_points = dset[-2]

In [64]:
last_points = torch.from_numpy(dset[-2:])
f.close()

In [65]:
last_points

tensor([[10.,  6.],
        [ 4.,  2.]])

In [66]:
a

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])